"""add type to work_experience

Revision ID: 3333dd175a0f
Revises: b3fd4c7a7529
Create Date: 2026-01-21 12:02:42.351975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3333dd175a0f'
down_revision: Union[str, Sequence[str], None] = 'b3fd4c7a7529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_experience', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_experience', 'type')
    # ### end Alembic commands ###
